name: "CI: Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup Just ðŸ“¦
        uses: extractions/setup-just@v3
      - name: Install the latest version of uv ðŸ“¦
        uses: astral-sh/setup-uv@v7
      - name: Install python ðŸ“¦
        uses: actions/setup-python@v6
      - name: Install dependencies ðŸ“¦
        run: just install
      - name: Run tests and benchmarks âœ…
        uses: CodSpeedHQ/action@v3
        with:
          run: just test
      - name: Upload coverage reports to Codecov ðŸ“¦
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: nanoflow
          plugins: pycoverage,compress-pycoverage
